server:
  port: 8090

spring:
  application:
    name: inventory-application
  jpa:
    defer-datasource-initialization: true
  # config r2dbc postgres
  r2dbc:
    url: r2dbc:postgresql://localhost:5432/postgres
    username: user
    password: password

logging:
  level:
    com.netflix.eureka: OFF
    com.netflix.discovery: OFF
    root: info
    org:
      springframework:
        r2dbc: DEBUG
        data:
          r2dbc:
            query: DEBUG

eureka:
  instance:
    appname: inventory-application
  client:
    enabled: true
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka/