server:
  port: 9093

spring:
  r2dbc:
    url: r2dbc:postgresql://localhost:5432/postgres
    username: user
    password: password

eureka:
  instance:
    appname: docs-application
  client:
    enabled: true
    register-with-eureka: true
    fetch-registry: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

swagger:
  config:
    refreshrate: 5000
