server:
  port: 5000

spring.cloud.stream:
  function:
    definition: processor
  bindings:
    processor-in-0:
      destination: order-processed
    processor-out-0:
      destination: order-updated
  kafka:
    binder:
      replication-factor: 1

service:
  endpoints:
    inventory: http://localhost:8082
#    payment: http://localhost:8082

spring:
  application:
    name: orchestrator-domain-service-app
  r2dbc:
    url: r2dbc:postgresql://localhost:5432/postgres
    username: user
    password: password
